name: Action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0
